---
  all:
    hosts:
      etcd-0:
        ansible_host: 46.101.35.114
      etcd-1:
        ansible_host: 46.101.35.114

      controlplane-0:
        ansible_host: 46.101.35.114
      controlplane-1:
        ansible_host: 46.101.35.114

      worker-0:
        ansible_host: 46.101.35.114
      worker-1:
        ansible_host: 46.101.35.114

      loadBalancer:
        ansible_host: 46.101.19.182
  
  children:
    rancher-2-kubernetes-nodes:
      children:
        etcd:
          hosts:
            etcd-0:
            etcd-1:
        controlplane:
          hosts:
            controlplane-0:
            controlplane-1:
        worker:
          hosts:
            worker-0:
            worker-1:
    rancher-2-load-balancers:
      hosts:
        loadBalancer: